config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :admins
  authenticate :admin do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web, at: "/relay_sauce_sidekiq"
  end
  
  resources :email_stashes do
    collection do
      put :selection
    end
  end
  #email_stashes
  get 'index_yahoo', to: 'email_stashes#index_yahoo', as: 'email_stashes/index_yahoo'
  get 'index_gmail', to: 'email_stashes#index_gmail', as: 'email_stashes/index_gmail'
  post 'create_recipient', to: 'email_stashes#create_recipient'

  resources :lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :charges

  get '/users/auth/google_oauth2/callback' => 'google_contacts#new'
  get '/users/auth/yahoo_oauth2/callback'  => 'yahoo_contacts#new'

  resources :email_templates

  get 'pricing', to: 'layouts#pricing', as: 'pricing'
  get 'privacy', to: 'layouts#privacy', as: 'privacy'
  get 'about', to: 'layouts#about', as: 'about'
  get 'yahoo_instruction', to: 'layouts#yahoo_instruction', as: 'yahoo_instruction'

  get :send_test_email, to: 'email_templates#send_test_email', as: :send_test_email

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  resources 'unsubscribes', only: :show

end

app/models/email_stash.rb
class EmailStash < ApplicationRecord
  # serialize :recipient_email_addresses, Array
  validates :recipient_email_address, presence: true
  validates_format_of :recipient_email_address, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/, on: :create
  validates :recipient_email_address, uniqueness: true

  scope :received_mail, -> {where(is_receive_mail: true)}
  def send_mail_name
    if recipient_first_name.present?
      recipient_first_name
    end
  end

  def recipient_full_name
    [recipient_first_name, recipient_last_name].join " "
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :user_mailers
  has_many :user_email_stashes
  has_many :selected_user_email_stashes, -> {selected}, class_name: UserEmailStash.name
  has_many :email_stashes, through: :selected_user_email_stashes

  def self.create_from_omniauth(params)
  	user = find_or_create_by(email: params.info.email, uid: params.uid)
    user.update({
  		token: params.credentials.token,
			name: params.info.name,
			avatar: params.info.image
    })
    user
  end
end

app/controllers/email_stashes_controller.rb
class EmailStashesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_email_stash, only: [:show, :edit, :update, :destroy]

  # GET /email_stashs
  # GET /email_stashs.json
  def index_gmail
    @u_email_stash = current_user.user_email_stashes.includes(:email_stash)
    @email_stash = EmailStash.new(source: "gmail")
    params[:selected] = true
  end

  def index_yahoo
    @u_email_stash = current_user.user_email_stashes.includes(:email_stash)
    params[:selected] = true
    @email_stash = EmailStash.new(source: "yahoo")
  end

  def create_recipient
    email_stash = EmailStash.where(recipient_email_address: new_email_stash_params[:recipient_email_address]).first
    source = new_email_stash_params[:source]
    if email_stash
      current_user.user_email_stashes.find_or_create_by email_stash_id: email_stash.id
      redirect_to(source == "gmail" ? email_stashes_index_gmail_path : email_stashes_index_yahoo_path)
    else
      @email_stash = EmailStash.new new_email_stash_params
      if @email_stash.save
        UserEmailStash.create user_id: current_user.id, email_stash_id: @email_stash.id
        redirect_to(source == "gmail" ? email_stashes_index_gmail_path : email_stashes_index_yahoo_path)
      else
        @u_email_stash = current_user.user_email_stashes.includes(:email_stash)
        render(source == "gmail" ? :index_gmail : :index_yahoo)
      end
    end
  end

  # GET /email_stashs/1
  # GET /email_stashs/1.json
  def show
    @email_stash = EmailStash.find(params[:id])
  end

  # GET /email_stashs/1/edit
  def edit
    
  end

  def selection
    # byebug
    @u_email_stash = UserEmailStash.where id: params[:u_email_stash].split(',')
    respond_to do |format|
      @u_email_stash.each do |e|
        if e.id.to_s.in?(params[:u_email_stash_ids].presence || [])
          e.update! selected: true
          redirect_path = params[:source] == "gmail" ? email_stashes_index_gmail_path : email_stashes_index_yahoo_path
          format.html { redirect_to redirect_path, notice: 'Email list was successfully updated.' }
        else
          e.update! selected: false
        end
      end
    end
    # respond_to do |format|
    #     if @email_stash.update
    #       format.html { redirect_to new_email_template_path, notice: 'Email list was successfully updated.' }
    #       # flash[:toastr] = "Updated emails!"
    #       format.json { render :show, status: :ok, location: new_email_template_path }
    #     end
    #   end
    
    
  end

  # POST /email_stashs
  # POST /email_stashs.json
  def create
    @email_stash = EmailStash.new(email_stash_params)

    respond_to do |format|
      if @email_stash.save
        format.html { redirect_to @email_stash, notice: 'Email stash was successfully created.' }
        format.json { render :show, status: :created, location: @email_stash }
      else
        format.html { render :new }
        format.json { render json: @email_stash.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /email_stashs/new
  def new
    @auth = request.env['omniauth.auth']['credentials']

    yahoo_gateway = YahooGateway.new(*@auth.values_at('token', 'expires_at', 'refresh_token'))
    @emails       = yahoo_gateway.fetch_contact_emails


    #make array of recipients
    # @stash = EmailStash.new(uid: current_user.uid, email: current_user.email, name: current_user.name, selected: true, recipient_email_addresses: @recipients)
    # @recipients = []
    # @emails.each do |d|
    #   @recipients << d
    # end
    # @stash.save

    # @count = EmailStash.where(uid: current_user.uid).count
    # @newlist = List.new(title: 'Facebook' + @count)

    # respond_to do |format|
    #   if @newlist.save
    #     format.html { redirect_to @list, notice: 'List was successfully created.' }
    #   end
    # end

    @email_stash = EmailStash.all

  end


  # PATCH/PUT /email_stashs/1
  # PATCH/PUT /email_stashs/1.json
  def update
    respond_to do |format|
      if @email_stash.update(email_stash_params)
        format.html { redirect_to @email_stash, notice: 'Email stash was successfully updated.' }
        # flash[:toastr] = "Updated emails!"
        format.json { render :show, status: :ok, location: @email_stash }
      else
        format.html { render :edit }
        format.json { render json: @email_stash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_stashs/1
  # DELETE /email_stashs/1.json
  def destroy
    @email_stash.destroy
    respond_to do |format|
      format.html { redirect_to email_stashs_url, notice: 'Email stash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_stash
      @email_stash = EmailStash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white stash through.
    def email_stash_params
      params.require(:email_stash).permit(:uid, :recipient_name, :email, :date_sent, :subject, :body, :recipient_email_address)
    end

    def new_email_stash_params
      params.require(:email_stash).permit(:email, :recipient_email_address, :source,
        :recipient_first_name, :recipient_last_name)
    end
end

app/views/email_stashes/_form.html.erb
<input type="checkbox" id="selectAll" class="selectbox">All Items<span id="showEmailCount" class="label--checkbox"></span></input>
<%= form_for(email_stash) do |f| %>
  <% if email_stash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(email_stash.errors.count, "error") %> prohibited this email_stash from being saved:</h2>

      <ul>
      <% email_stash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :recipient_email_addresses %>
    <%= f.text_field :recipient_email_addresses %>
  </div>


  <div class="field">
    <%= f.label :selected %>
    <%= f.check_box :selected %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
$("#selectAll").select_all({show_count: "checked",
  attach_count_to: "#showEmailCount"})
</script>

app/views/email_stashes/_recipient_form.html.erb
<div class="recipient_form">
  <%= form_for @email_stash, url: create_recipient_path do |f| %>
    <% if @email_stash.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@email_stash.errors.count, "error") %> prohibited this recipient from being saved:</h3>

        <ul>
        <% @email_stash.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
      <div class="row" label="recipient email address">
        <%= f.text_field :recipient_email_address, class: 'form-control', placeholder: 'recipient email address' %>
      </div>
      <div class="row" label="recipient first name">
        <%= f.text_field :recipient_first_name, class: 'form-control', placeholder: 'recipient first name' %>
      </div>
      <div class="row" label="recipient last name">
        <%= f.text_field :recipient_last_name, class: 'form-control', placeholder: 'recipient last name' %>
      </div>
      <div class="form-group hidden">
        <%= f.label :source %><br>
        <%= f.text_area :source,  class: 'form-control', value: source %>
      </div>
      <div class="form-group hidden">
        <%= f.label :email %><br>
        <%= f.text_area :email,  class: 'form-control', value: current_user.name %>
      </div>
    
    </fieldset>

    <div class="actions">
      <%= f.submit "Add new recipient", class: 'btn btn-xs btn-success' %>
      <button type="button" class="cancel btn btn-small btn-danger" onclick="hide_recipient_form();">Cancel</button>
    </div>

  <% end %>
  
</div>

<script type="text/javascript">
  function show_recipient_form() {
    document.getElementsByClassName("recipient_form")[0].style.display="block";
    document.getElementsByClassName("new-recipient")[0].style.display="none";
  }

  function hide_recipient_form() {
    document.getElementsByClassName("recipient_form")[0].style.display="none";
    document.getElementsByClassName("new-recipient")[0].style.display="block";
    $("#error_explanation").remove();
    $("#email_stash_recipient_email_address").val("");
    $("#email_stash_recipient_first_name").val("");
    $("#email_stash_recipient_last_name").val("");
  }

  var isShowForm = <%= @email_stash.errors.any? %>
  if(isShowForm) {
    show_recipient_form();
  };

</script>

app/views/email_stashes/edit.html.erb
<div class="steps-nav"><ol><li class="active">Import contacts</li><li>Create template</li><li>Review and Send</li></ol></div>
<h1>Editing email list</h1>

<%= render 'form', email_stash: @email_stash %>

<%= link_to 'Show', @email_stash %> |
<%= link_to 'Back', email_stash_path %>

app/views/email_stashes/index.html.erb
<div class="steps-nav"><ol><li class="active">Import contacts</li><li>Create template</li><li>Review and Send</li></ol></div>
<div class="jumbotron">
    <h1>Nice list, dude. </h1>
    	<p class="lead">We imported <strong><%= @email_stash.count%> email addresses</strong> from your Facebook friends list. Select which contacts you want to send to.</p>
    
    <hr>


    <%= form_tag selection_email_stashes_path, method: :put do %>
	    <% if @email_stash.where(source: 'yahoo').exists? %>

		    <!-- <h2>Facebook</h2> -->
			<ul  style="overflow: scroll;max-height: 300px;padding:10px;">
			
				<% @email_stash.where(source: 'yahoo').each do |y| %>
				<li>
					<%= check_box_tag "email_stash_ids[]", y.id%>
					<%#= y.id %>
					<%=  y.recipient_email_address %>
					<%= y.selected %>

				</li>
				<%end %>
			</ul>
		<% end %>

	<%= submit_tag "Save selection", class: 'btn btn-success' %>
	<% end %>





	
</div>
<%#= link_to 'Edit', edit_email_stash_path(@email_stash) %>
<% if @email_stash.where(source: 'yahoo', selected: true).count > 0%>
<%= link_to "Next step: Email template", new_email_template_path(), class: "btn btn-lg btn-primary pull-right" %>
<% end %>

app/views/email_stashes/index_gmail.html.erb
<div class="steps-nav"><ol><li class="active"><span class="hidden-xs">Import contacts</span></li><li><span class="hidden-xs">Create template</span></li><li><span class="hidden-xs">Review and Send</span></li></ol></div>
<div class="jumbotron">
    <h1>Nice list! </h1>
      <p class="lead">We've imported <strong><%= @u_email_stash.count%> email addresses</strong> from your contacts. Select which contacts you want to send to.</p>
    
    <hr>

    <strong><span class="showCarCount"></span></strong> <br/><input type="checkbox" id="selectAll">&nbsp; Select all</input> 
    <%= form_tag selection_email_stashes_path, method: :put do %>
      <% if @u_email_stash.exists? %>

        <%= hidden_field_tag :u_email_stash, @u_email_stash.map(&:id).join(',') %>
        <%= hidden_field_tag :source, "gmail" %>
      <ul class="stash-list">
      
        <% @u_email_stash.each do |y| %>
        <li>
          <% stash = y.email_stash %>
          <%= check_box_tag "u_email_stash_ids[]", y.id, y.selected, class: "selectable"%>
          <%= stash.recipient_first_name%>
          <%= stash.recipient_last_name%>&nbsp;-
          <%=  stash.recipient_email_address %>
          <%#= y.selected %>

        </li>
        <%end %>
      </ul>
    <% end %>
    
  <%= submit_tag "Save selection", class: 'btn btn-success' %>
  <button type="button" class="new-recipient btn btn-small btn-primary" onclick="show_recipient_form();">Add new recipient</button>
  <% end %>

  <%= render "recipient_form", source: "gmail" %>

</div>
<%#= link_to 'Edit', edit_email_stash_path(@email_stash) %>
<% if @u_email_stash.selected.count > 0%>
  <%= link_to "Next step: Email template", email_templates_path(), class: "btn btn-lg btn-primary pull-right" %>
<% end %>

<script type="text/javascript">
  $("#selectAll").select_all({
    show_count: "checked",
    attach_count_to: ".showCarCount"
  });
</script>

app/views/email_stashes/index_yahoo.html.erb
<div class="steps-nav"><ol><li class="active"><span class="hidden-xs">Import contacts</span></li><li><span class="hidden-xs">Create template</span></li><li><span class="hidden-xs">Review and Send</span></li></ol></div>
<div class="jumbotron">
    <h1>Nice list! </h1>
      <p class="lead">We've imported <strong><%= @u_email_stash.count%> email addresses</strong> from your contacts. Select which contacts you want to send to.</p>
    
    <hr>
    <strong><span class="showCarCount"></span></strong>
    <br/>
    <input type="checkbox" id="selectAll">&nbsp; Select all</input> 
    <%= form_tag selection_email_stashes_path, method: :put do %>
      <% if @u_email_stash.exists? %>

        <%= hidden_field_tag :u_email_stash, @u_email_stash.map(&:id).join(',') %>
        <%= hidden_field_tag :source, "yahoo" %>
      <ul class="stash-list">
      
        <% @u_email_stash.each do |y| %>
        <li>
          <% stash = y.email_stash %>
          <%= check_box_tag "u_email_stash_ids[]", y.id, y.selected, class: "selectable"%>
          <%= stash.recipient_first_name%>&nbsp;
          <%= stash.recipient_last_name%>&nbsp;-
          <%=  stash.recipient_email_address %>
          <%#= y.selected %>

        </li>
        <%end %>
      </ul>
    <% end %>
    
  <%= submit_tag "Save selection", class: 'btn btn-success save-selection' %>
  <button type="button" class="new-recipient btn btn-small btn-primary" onclick="show_recipient_form();">Add new recipient</button>
  <% end %>

  <%= render "recipient_form", source: "yahoo" %>

</div>
<%#= link_to 'Edit', edit_email_stash_path(@u_email_stash) %>
<% if @u_email_stash.selected.count > 0%>
  <%= link_to "Next step: Email template", email_templates_path(), class: "btn btn-lg btn-primary pull-right next-email-temp" %>
<% end %>

<script type="text/javascript">
  $("#selectAll").select_all({
    show_count: "checked",
    attach_count_to: ".showCarCount"
  });
</script>

app/views/email_stashes/new.html.erb
<div class="steps-nav"><ol><li class="active">Import contacts</li><li>Create template</li><li>Review and Send</li></ol></div>
<div class="jumbotron">
    <h1>Nice. We got'em.</h1>
    <p class="lead">Here is the list we pulled from your contact list.</p>
	<ul  style="overflow: scroll;max-height: 800px;padding:10px;">
	<% @email_stash.each do |d| %>
		<li>
			<%#= d.name %>
			<p><%= d.recipient_email_address %></p>
		</li>
	<%end %>
	</ul>
</div>
<%#= link_to 'Edit', edit_email_stashes_path(@email_stash) %> |
<%#= link_to 'Back', email_stashes_path %>

app/views/email_stashes/show.html.erb
<div class="steps-nav"><ol><li class="active"><span class="hidden-xs">Import contacts</span></li><li><span>Create template</span></li><li><span>Review and Send</span></li></ol></div>
<div class="jumbotron">
	<h1>Let's make this saucy.</h1>
  	<hr/>
  	<% @email_stash.recipient_email_addresses.each do |f| %>
  		<%= f%>
  	<% end %>
</div>


<%= link_to 'Edit', edit_email_stash_path(@email_stash) %> |
<%#= link_to 'Back', email_stash_path %>