releases/20170815170328/config/routes.rb
Rails.application.routes.draw do
  resources :email_stashes do
    collection do
      put :selection
    end

    
  end
  #email_stashes
  get 'index_yahoo', to: 'email_stashes#index_yahoo', as: 'email_stashes/index_yahoo'
  get 'index_gmail', to: 'email_stashes#index_gmail', as: 'email_stashes/index_gmail'

  resources :lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :charges

  get '/users/auth/google_oauth2/callback' => 'google_contacts#new'
  get '/users/auth/yahoo_oauth2/callback'  => 'yahoo_contacts#new'

  resources :email_templates

  get 'pricing', to: 'layouts#pricing', as: 'pricing'
  get 'privacy', to: 'layouts#privacy', as: 'privacy'
  get 'about', to: 'layouts#about', as: 'about'
  get 'yahoo_instruction', to: 'layouts#yahoo_instruction', as: 'yahoo_instruction'

  get :send_test_email, to: 'email_templates#send_test_email', as: :send_test_email

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

releases/20170815170328/app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

	def index
	end

	def pricing
	end

end

releases/20170815170328/app/views/layouts/_facebook.html.erb
<script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1895133730751635',
        xfbml      : true,
        version    : 'v2.9'
      });
      FB.AppEvents.logPageView();
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

releases/20170815170328/app/views/layouts/_faq.html.erb
<br/>
<div class="faq">

  <h1>Frequently Asked Questions</h1>
  <ul>
    <li data-toggle="collapse" data-target="#first">Why choose Relay Sauce? <span class="glyphicon glyphicon-plus"></span></li>
    <div id="first" class="collapse">
      Statistical fact: less than 5% of your Facebook friends know about your recent crowdfunding campaign.
We increase that dramatically by providing you simple personalization tools to send an email message to each friend and we make your message to be more personal (like using the recipient's first name).
Personal messages increase your ROI (return) dramatically (vs. group messaging that people tend to ignore and wall posts that only 4-5% of your friends actually see).
<!-- We double check and make an extra effort that each message reaches the recipients inbox folder, and we try to calculate the best time of the day to send each message (for each recipient) in order to increase your ROI and much more. -->
    </div>
    <li data-toggle="collapse" data-target="#second">What’s the average ROI (return on investment)?<span class="glyphicon glyphicon-plus"></span></li>
    <div id="second" class="collapse">
The average ROI is about 1:15. This means that if you have ~ 500-1000 friends, the cost to use the service will be around $60 and you can raise about $1000-$2000. Of course it varies from campaign to campaign and mainly depends on your campaign, perks you offer, your message and your friends. Although we helped many campaigns to gain their first contribution, we recommend using Relay Sauce only after you raised a total of 100 USD from 4 people (or more) to show some social proof your campaign works.
    </div>
    <li data-toggle="collapse" data-target="#third">What will happen to my contacts list after my order?<span class="glyphicon glyphicon-plus"></span></li>
    <div id="third" class="collapse">
      We will never share, sell or abuse the information you share with us. Please see more in our <%= link_to "privacy policy", privacy_path%>
    </div>

    <li data-toggle="collapse" data-target="#four">What's the secret sauce?<span class="glyphicon glyphicon-plus"></span></li>
    <div id="four" class="collapse">
Less than 5% of your friends know about your recent crowdfunding campaign!
We increase that dramatically by providing you simple personalization tools to send a magical email message to each friend.
Personal messages increase your ROI (return) dramatically vs. group/BCC messaging that people tend to ignore and public posts (or tweets) that only 4-5% of your friends actually see. 
    </div>

    <li data-toggle="collapse" data-target="#five">What will happen to my contacts list after my order?<span class="glyphicon glyphicon-plus"></span></li>
    <div id="five" class="collapse">
      We will never share, sell or abuse the information you share with us. Please see more in our <%= link_to "privacy policy", privacy_path%>
    </div>
  </ul>
  
</div>

<!-- 
2. Tell me more about the 100% Risk Free Program: “Fundraising Guaranteed”
In order to make any Kickstarter / Indiegogo successful, the campaign owner needs to take risks and invest a lot of time and money.
We want to reduce those risks to minimum, and we make sure that you will raise funds through our services.
Please visit this URL to learn more: Fundraising Guaranteed Program.

4. Who compose the message? Who is in charge of the wording?
You are! The person that using the service is composing the message for his selected friends. We’ve also created a doc with some tips of how to create a good message to increase the ROI (return).
See also: How to Craft a Message for your Email Blast.

5. What’s the difference between the Green Inbox and Facebook promoted posts?
As a Facebook page owner you can use promoted posts to increase the exposure of a single specific post in the newsfeed of your page fans.
The Green Inbox is a complementary service that enables you to send a private email message to each friend on your Facebook individual account (and also send private messages to your twitter followers, linkedin connections, email, phone contacts etc.).

6. Can I use Green Inbox to message my Facebook page fans?
No. You can use the service to message your Facebook friends on your Facebook individual account or your twitter followers (linkedin etc.).

7. My campaign ends in 72 hours! Can I use your service?
Usually, it takes up to 48-72 hours to process your order and get the payment confirmation - so please don’t wait for the last minute to place your order.

8. Can I combine multiple accounts under the same order/payment.
Since we review each order individually and we have a relatively high cost for each order we can not combine multiple accounts under the same order.
Please take into consideration that once you place an order - your payment is a one-time payment for this specific order you placed (and cannot be extended to other accounts / recipients).

9. How do I limit my order to a specific amount of Facebook friends?
Use this URL after login to limit your friend list to 500 Facebook friends:
http://www.greeninbox.com/friends?limit=500
You can change the number (500) to any number you wish and limit your friend list accordingly.

10. How do I exclude Facebook friends I’ve already messaged before?
Use this URL after login to exclude Facebook friends you’ve already messaged through Green Inbox:
http://www.greeninbox.com/friends?continue=1

11. Do you provide discounts for large volume orders?
No. Never. Our prices are fixed for all.
We do offer a refer program where existing clients can use our website for free.
Read more here: www.greeninbox.com/invite.
Please note that this program is only for people that already paid to use our website.



13. Does Green Inbox sends Emails or Facebook chat messages?
Facebook changed the API on April-2015, and since then we shifted to personal emails.
The emails method is 100% safe. On average, the results / $ return is a bit better than before (emails are better than chat).
Facebook chat messages method is no longer possible.

14. I don't have a yahoo account. What can I do? (Facebook Package related)
The only way to import your Facebook friends emails is through a yahoo email account.
If you do not have a yahoo email account, it takes 2 minutes to create a new yahoo email account.
Once we import the emails of your friends, you can close the yahoo mail account / never use it again.
The sender email for your order can be any email you'd like.

15. I used the Facebook, Gmail, Linkedin & Twitter packages and raised ~$5,000 USD through Green Inbox.
How else can I promote my campaign?
Ask close friends & family to message their network of friends about your campaign through Green Inbox.
Campaigners that used our website and raised 50,000 USD (or more) used a large team of friends and family.

We would recommend starting with 2-3 members (can be family, friends, friends of friends etc.) and see if this works for you.
This "method" also helped the Coolest Cooler Kickstarter raise more than $13m.

16. Can I use Green Inbox to promote my Event or Facebook page?
Yes. You can use our website to promote whatever you'd like. -->

releases/20170815170328/app/views/layouts/_toastr.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
     toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
</script>
<% end %>

releases/20170815170328/app/views/layouts/about.html.erb
<div class="jumbotron">
  <h1>Yer gonna need some sauce on that.</h1>
  <ul>
  <li>1. Rapid email delivery at your service.</li>
  <li>2. If you don't make a return of at least the amount of our fee, we'll refund you.</li> 
  <li>3. We never sell your info or spam you.</li>
  </ul>

  <!-- <hr> -->

  
</div>

<style type="text/css">
	ul{
		padding:0;
		margin:0;
	}
</style>

releases/20170815170328/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Relay Sauce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
    <script type="text/javascript" src="https://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  
  <body>
  
    <%= render 'layouts/facebook' %>
    <div class="container">
          <div class="header clearfix">
            <nav>
              <ul class="nav nav-pills pull-right">

                <li role="presentation"><%= link_to "Pricing", pricing_path %></li>
                <!-- <li role="presentation"><%#= link_to "About", about_path %></li> -->
                <li>
                  <% if user_signed_in? %>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >
                    <%= image_tag current_user.avatar, class: "img-responsive img-circle dropdown-toggle"%>
                  </a>
                  <ul class="dropdown-menu">
                    <li style="padding-left: 10px;"><%= current_user.name %></li>
                    <li><%= link_to "Logout", destroy_user_session_url, method: :delete %></li>
                  </ul>
                  <% end %>
                </li>
              </ul>
            </nav>
            <div class="logo"><a href="/"><span class=" glyphicon glyphicon-send"></span> <span class="">RelaySauce</span></a></div>
          </div>
      <%= yield %>
      <%= render 'layouts/toastr' %>
    </div>
    <footer class="footer">
      <div class="container">
        <ul>
          <li><%= link_to 'Privacy', privacy_path, class: 'btn' %></li>
          <li><%= link_to 'Contact', new_contact_path, class: 'btn' %></li>
        </ul>
      </div>
      
    </footer>
  </body>

</html>

releases/20170815170328/app/views/layouts/pricing.html.erb
<div class="jumbotron">
  <h1><span class="glyphicon glyphicon-usd"></span>0.06 per email</h1>
  <p>Send emails to all your Facebook friends. We use Yahoo to fetch your facebook friends. Please follow these <strong><%= link_to "easy instructions", yahoo_instruction_path %></strong> to use this option.</p>

  <!-- <hr> -->

  
</div>
<div class="price-levels">
  <div style="background: #38afff;">
    <h2>500 emails <span class="price-tag"><span class="glyphicon glyphicon-usd"></span>30</span></h2>
  </div>
  <div style="background: #3892FF;">
    <h2>1000 emails <span class="price-tag"><span class="glyphicon glyphicon-usd"></span>60</span></h2>
  </div>
  <div style="background: #394EFF;">
    <h2>2000 emails <span class="price-tag"><span class="glyphicon glyphicon-usd"></span>120</span></h2>
  </div>
  <div style="background:  #3825FF;">
    <h2>2K+ emails <span class="price-tag"><small class="white">Contact us to discuss</small></span></h2>
  </div>

</div>

<hr>
<h2></h2>
<p></p>
<p>* Minimum 500 emails</p>

releases/20170815170328/app/views/layouts/privacy.html.erb
<h1>PRIVACY POLICY</h1>
<p>
As used herein, “the Site” refers to the service and network located at www.relaysauce.com and their subdomains, mobile version(s), downloadable apps, and any associated applications that are owned and/or operated by Relay Sauce (collectively, “us,” “we,” “our,” or “the Company”). By using the Site you indicate your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you are not permitted to access the Site and you should not do so.</p>
<p>
Our postal address is:

Relay Sauce
2556 W Chicago Ave
Chicago, IL 60622
</p>
<p>
We can also be contacted via email: <a href="mailto:relaysauce@gmail.com">relaysauce@gmail.com</a>.
</p>
<p>
We reserve the right to change or otherwise update this Privacy Policy at any time. Such changes or updates are effective immediately after we give notice of the change or update, which we may do by revising the “Last Updated” date at the bottom of this Privacy Policy or by otherwise posting on the Site, by email or conventional mail, and/or by any other means that provides reasonable notice. Your use of the Site after such notice is posted confirms that you accept these changes or updates. If you are concerned about how your information is used, you should periodically review this Privacy Policy.
</p>

<h2>Introduction</h2>
<p class="">We understand and respect your desire for privacy. To that end, we would like you to know how we use the information you provide to us.</p>
<p>
We (both directly and through third parties) collect personally identifying information when you access any pages on the Site or register for the Site. If you provide us with your email address, you will not receive an emails except those which pertain to your order with Relay Sauce. We collect non-personally-identifiable information (such as your IP address or domain,  or information about your use of the Site) both directly and through third parties for purposes of site administration, to improve and customize user experiences, and to compile aggregate information about usage of the Site.</p>

<p>
Payments will be processed by a third party processor, Stripe, and is not stored on Relay Sauce servers.  Relay Sauce will collect specific Personal Information required for Stripe to process payments. This includes credit card numbers, billing addresses, security (CVV) codes and any other relevant financial information.  All such information will be transferred directly to Stripe and not retained, stored or used by Relay Sauce without prior consent. In the case of subscription services, such as the Relay Sauce’ VIP program, tokenization will be used to associate payment information to your account on a monthly basis.  All such transferred information is subject to the privacy policy of Stripe rather than this policy. </p>
<p>
Be sure to review all privacy policies published by our third-party providers and contact them directly if you have questions as they may have privacy terms that differ from our Privacy Policy.</p>
<p>
We have implemented appropriate safeguards to help prevent unauthorized access, maintain data security, and make proper use of the information we collect. However, no transmission of data over the Internet is guaranteed to be completely secure. Thus, while we strive to protect your personal information, we cannot absolutely guarantee the security of any information you provide to us.</p>
<p>
Personal information collected from our Site may be disclosed when legally required to do so, at the request of governmental authorities conducting an investigation, to verify compliance with the policies governing our Site and applicable laws, or to protect against missed or unauthorized use of our Site.</p>
<p>
Policy for Minors
Use of the Site is intended for persons over the age of 13 years old. No information should be submitted to or posted on the Site by any Minor (a user younger than 13 years of age). If a minor between the ages of 13 and 18 accesses or registers for the Site, or signs up to receive our newsletter, they should do so with parental or guardian consent. Unless otherwise disclosed during collection, we do not knowingly provide any personally identifying information about Minors, regardless of its source, to third parties, nor is this information knowingly used by us for any marketing or promotional purposes.</p>
<p>
By registering for this site you are certifying that you are at least 13 years old.</p>
<p>
Policy for Users
We collect personal information from Site users over 13 years of age in order to provide users with a personalized online experience and to provide our advertisers a way to reach the right audience. We may share the personal and aggregate information we collect with our affiliates and other sites operated by and for us. On a confidential basis, we may also share personal information with our corporate affiliates or consultants, or with third parties that perform a particular service on our behalf (such as fulfilling orders or for general administration purposes for the Site). We may share aggregate information with third parties for advertising and promotional purposes. If all or part of the Company is sold, merged, or is otherwise transferred to another entity, the information you have provided on or through the Site may be transferred to such entity as part of that transaction. We may also disclose personal information in response to legal process, such as a request by law enforcement, a court order or subpoena, or to protect the integrity of the Site if we believe that a user has committed unlawful or otherwise harmful acts (please refer to our Terms of Service).</p>
<p>
With the permission of users 13 years or older, information submitted at the time of registration or submission may be used for marketing and promotional purposes by us and, also with the permission of the user, may be shared by us with companies that have agreed with us to use this information only for the marketing and promotion of its products and services.</p>
<p>
If any individual submits content for publication, we may publish his or her name and any other information submitted by that individual.</p>
<p>
If a user elects to use our “Email to a Friend” referral service for informing a friend about the Site, we ask for the friend’s email address, and we will send an email in response to the user’s request inviting their friend to visit the Site. This information is stored at the Site solely for the purpose of sending the email.</p>

<p>
Public Forums, Comments, and Reviews
Whenever you voluntarily disclose personal information online in forums or similar posting areas, the information can be reviewed and collected by anyone. Therefore, do not post any information that you do not want to be made available to the general public. We are not responsible for unsolicited communications that arise from your postings on the Site.
</p>
<!-- <p>
Purchase of Products or Services from SimpleTruths.com
If you purchase a product or service from the Site, information may be collected from you, including your credit card and contact information, for transfer to and use by third-party providers of the product or service. Your credit card and billing information is only retained by our Site if you choose to do so. Any credit card information that is retained is done so using encrypted technologies. Unless otherwise stated, we do not have any responsibility in connection with such purchases and all transactions and use of any customer information are the sole responsibility of the product/service provider. Be sure to review the product/service provider’s privacy policy and contact them directly if you have any questions. They may have privacy terms that differ from our Privacy Policy.</p>
<p> -->

<h2>Use of Personal Information</h2>
Use of Cookies
Cookies are pieces of information that a website transfers to an individual’s computer for record keeping purposes. Cookies make web surfing easier by saving your passwords, preferences, and purchase information while you’re online. The use of cookies is an industry standard practice and can be found on nearly all major websites.
</p>
<p>
We may use cookies, among other purposes, to record session and Site usage information, to help us see which areas are popular and which are not, to alert users to new areas and products that we think might be of interest to them when they return to the Site, and to record past activity to provide better service when users return to the Site, and to perform remarketing to users who have previously visited the Site. This helps us to target products and recommendations based on user interests, and also improve and update the Site based on such data as a total number of users and pages viewed. This information is most easily tracked with cookies.
</p>

<p>
The use of cookies sent by third-party servers is standard in the Internet industry. Most browsers are initially set to accept cookies. If you choose to remove or block cookies, it is possible that some parts of the Site, such as the shopping and contest/sweepstakes areas, will not function properly if you do so.
</p>
<p>
Use of IP Addresses
An IP address is a number that is automatically assigned to your computer by your Internet Service Provider (ISP) whenever you log on the the Internet. Web servers automatically identify your computer by its IP address, so when a user requests pages from the Site, our servers log the user’s IP address. The IP addresses of our users are collected only for the purposes of system administration and to report aggregate information to our advertisers, our corporate affiliates or consultants, or with third parties that perform a particular service on our behalf. We do not combine IP addresses with any personally identifying information, nor do we compile any session activity reports by IP address.
</p>
<p>
Use of Email Address
Any email address that you provide provide when you login/register for the Site, or make a purchase through the Site will be retained and may be used to communicate with you regarding order status and updates</p>
<p>
To unsubscribe from any communications from us, follow the “unsubscribe” link at the bottom of any communication you receive. You can also unsubscribe from the promotional and marketing emails you receive from the Site’s partners by following the “unsubscribe” link at the bottom of emails from such partners. You can also unsubscribe by contacting us and requesting to have your information removed from our list.
</p>

<p>
If you supply us with a telephone number online, you will only receive contact from us regarding information on orders that have been placed online or through our customer service.
</p>
<!-- <p>
Third-Party Advertising
We may use third-party advertising companies and advertising networks to serve ads to you on our behalf when you visit the Site. These companies may use information (not including your name, address, email address, or telephone number) about your visits to the Site and other websites in order to provide advertisements about goods and services of interest to you.
</p> -->
<p>
Contact Us
If you feel that our Site is not following the stated information policy or have questions and concerns, you may contact us at any time.
</p>
<p>
Last updated and effective as of: 7/25/2017</p>

releases/20170815170328/app/views/layouts/yahoo_instruction.html.erb
<div class="jumbotron yahoo_instruction">
	<h1>Quickstart</h1>
 
  <div class="">
    <p>We use Yahoo to import your FB friends <small>(FB has decommissioned this feature on their API)</small>.</p>
    <ol>
      <li>Login or sign up for a <a target="_blank" href="https://www.yahoo.com/">yahoo account</a>. <br/><small>(delete it afterward if you want)</small></li>
      <li>Select 'contacts' - 2nd choice from left menu.</li>
      <li>Choose 'Import Facebook'</li>
      <li>Return to the Relay Sauce app.</li>
    </ol>
    <br/>
  </div>
  <div class="">
    <%= video_tag "yahoo-signup.webm", style: "width:100%", controls: true, autoplay: true%>
  </div>
 
</div>

<style type="text/css">
.yahoo_instruction .jumbotron{
		padding-top:0;
	}
.yahoo_instruction	ol{
		margin:0;
		

		
	}
.yahoo_instruction	li{
			list-style-type: decimal;
			color:#777;
			padding:1rem;
		}
</style>