releases/20170815170328/config/routes.rb
Rails.application.routes.draw do
  resources :email_stashes do
    collection do
      put :selection
    end

    
  end
  #email_stashes
  get 'index_yahoo', to: 'email_stashes#index_yahoo', as: 'email_stashes/index_yahoo'
  get 'index_gmail', to: 'email_stashes#index_gmail', as: 'email_stashes/index_gmail'

  resources :lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :charges

  get '/users/auth/google_oauth2/callback' => 'google_contacts#new'
  get '/users/auth/yahoo_oauth2/callback'  => 'yahoo_contacts#new'

  resources :email_templates

  get 'pricing', to: 'layouts#pricing', as: 'pricing'
  get 'privacy', to: 'layouts#privacy', as: 'privacy'
  get 'about', to: 'layouts#about', as: 'about'
  get 'yahoo_instruction', to: 'layouts#yahoo_instruction', as: 'yahoo_instruction'

  get :send_test_email, to: 'email_templates#send_test_email', as: :send_test_email

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

releases/20170815170328/app/models/list.rb
class List < ApplicationRecord
end

releases/20170815170328/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:uid, :customer_email, :name, :subject, :body, :recipients, :title, :date_sent, :select)
    end
end

releases/20170815170328/app/helpers/lists_helper.rb
module ListsHelper
end

releases/20170815170328/app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div class="field">
    <%= f.label :customer_email %>
    <%= f.text_field :customer_email %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :recipient_email_address %>
    <%= f.text_field :recipient_email_address %>
  </div>

  <div class="field">
    <%= f.label :date_sent %>
    <%= f.date_select :date_sent %>
  </div>

  <div class="field">
    <%= f.label :select %>
    <%= f.check_box :select %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

releases/20170815170328/app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

releases/20170815170328/app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Customer email</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Body</th>
      <th>Recipient email address</th>
      <th>Date sent</th>
      <th>Select</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.uid %></td>
        <td><%= list.customer_email %></td>
        <td><%= list.title %></td>
        <td><%= list.subject %></td>
        <td><%= list.body %></td>
        <td><%= list.recipients %></td>
        <td><%= list.date_sent %></td>
        <td><%= list.select %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

releases/20170815170328/app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

releases/20170815170328/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @list.uid %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @list.customer_email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @list.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @list.body %>
</p>

<p>
  <strong>Recipient email address:</strong>
  <%= @list.recipient_email_address %>
</p>

<p>
  <strong>Date sent:</strong>
  <%= @list.date_sent %>
</p>

<p>
  <strong>Select:</strong>
  <%= @list.select %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>