config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :admins
  authenticate :admin do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Sidekiq::Web, at: "/relay_sauce_sidekiq"
  end
  
  resources :email_stashes do
    collection do
      put :selection
    end
  end
  #email_stashes
  get 'index_yahoo', to: 'email_stashes#index_yahoo', as: 'email_stashes/index_yahoo'
  get 'index_gmail', to: 'email_stashes#index_gmail', as: 'email_stashes/index_gmail'
  post 'create_recipient', to: 'email_stashes#create_recipient'

  resources :lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :charges

  get '/users/auth/google_oauth2/callback' => 'google_contacts#new'
  get '/users/auth/yahoo_oauth2/callback'  => 'yahoo_contacts#new'

  resources :email_templates

  get 'pricing', to: 'layouts#pricing', as: 'pricing'
  get 'privacy', to: 'layouts#privacy', as: 'privacy'
  get 'about', to: 'layouts#about', as: 'about'
  get 'yahoo_instruction', to: 'layouts#yahoo_instruction', as: 'yahoo_instruction'

  get :send_test_email, to: 'email_templates#send_test_email', as: :send_test_email

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  resources 'unsubscribes', only: :show

end

app/controllers/yahoo_contacts_controller.rb
class YahooContactsController < ApplicationController
  def new
    @auth = request.env['omniauth.auth']['credentials']

    yahoo_gateway = YahooGateway.new(*@auth.values_at('token', 'expires_at', 'refresh_token'))
    @emails       = yahoo_gateway.fetch_contact_emails

    LoadOrCreateEmailStash.new(current_user, @emails, "yahoo").call

    redirect_to email_stashes_index_yahoo_url
    @u_email_stash = current_user.user_email_stashes.includes(:email_stash)

  end

end

app/views/yahoo_contacts/new.html.erb
<div class="steps-nav"><ol><li class="active">Import contacts</li><li>Create template</li><li>Review and Send</li></ol></div>
<div class="jumbotron">
    <h1>Cool email addresses, dude.</h1>
    <hr/>
    <ul>
    	<% @emails.each_with_index do |p, i|%>
    	<li><%= p[:first_name] %> <%= p[:last_name] %> ~ <%= p[:email]%> </li>
    	  
    	<% end %>
    </ul>
  
  <%= link_to "Save list", email_stashes_path(), class: "btn btn-success" %>
</div>

<%#= link_to "Next step: Email template", new_email_template_path(), class: "btn btn-lg btn-primary pull-right" %>